[package]
name = "disprg2"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
cross = "0.2.5"
csv = "1.3.0"
json = "0.12.4"
openssl = { version = "0.10", features = ["vendored"] }
reqwest = {version =  "0.11.13", features = ["blocking", "json"] }

